SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `#__allevents_activities` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(400)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `default`          INT(1)                    DEFAULT '0',
  `agenda_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `vignette`         VARCHAR(100)              DEFAULT NULL,
  `created_date`     DATETIME                  DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_agenda` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED          DEFAULT '0',
  `titre`            VARCHAR(400)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `created_date`     DATETIME                  DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT '0',
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT '0',
  `template`         VARCHAR(100)              DEFAULT NULL,
  `vignette`         VARCHAR(100)              DEFAULT NULL,
  `contact_id`       INT(11) UNSIGNED          DEFAULT '0',
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `modele`           MEDIUMTEXT,
  `checked_out`      INT(11)                   DEFAULT NULL,
  `checked_out_time` DATETIME                  DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)                   DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_contact` (`contact_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_albums` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(100)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `default`          TINYINT(1)                DEFAULT '0',
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `created_date`     DATE             NOT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `agenda_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `album_comp_id`    VARCHAR(200)              DEFAULT NULL,
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_categories` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `section_id`       INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `titre`            VARCHAR(100)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `created_date`     DATETIME                  DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `default`          TINYINT(1)       NOT NULL DEFAULT '0',
  `vignette`         VARCHAR(100)              DEFAULT NULL,
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_section` (`section_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_countries` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(100)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `isocode`          VARCHAR(2)                DEFAULT 'FR',
  `default`          TINYINT(1)                DEFAULT '0',
  `agenda_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `latitude`         VARCHAR(20)               DEFAULT NULL,
  `longitude`        VARCHAR(20)               DEFAULT NULL,
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `created_date`     DATETIME                  DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 4;

CREATE TABLE IF NOT EXISTS `#__allevents_enrolments` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `event_id`         INT(11) UNSIGNED NOT NULL,
  `contact_id`       INT(11) UNSIGNED          DEFAULT NULL,
  `rang`             INT(11) UNSIGNED          DEFAULT NULL,
  `dossard`          INT(11)                   DEFAULT NULL,
  `temps`            VARCHAR(20)               DEFAULT NULL,
  `categorie`        VARCHAR(20)               DEFAULT NULL,
  `rang_categorie`   INT(11) UNSIGNED          DEFAULT NULL,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `url`              VARCHAR(200)              DEFAULT NULL,
  `commentaire`      VARCHAR(200)              DEFAULT NULL,
  `enroldate`        DATETIME                  DEFAULT NULL,
  `user_id`          INT(11) UNSIGNED          DEFAULT NULL,
  `access`           INT(1)                    DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `pending`          TINYINT(1)                DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reminder_date`    DATETIME                  DEFAULT NULL,
  `section_id`       INT(11) UNSIGNED          DEFAULT NULL,
  `category_id`      INT(11) UNSIGNED          DEFAULT NULL,
  `points`           INT(11) UNSIGNED          DEFAULT NULL,
  `enroltype`        INT(11) UNSIGNED          DEFAULT '0',
  `locked`           TINYINT(1)                DEFAULT '0',
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_pending` (`pending`),
  KEY `ndx_published` (`published`),
  KEY `fky_event` (`event_id`),
  KEY `fky_section` (`section_id`),
  KEY `fky_category` (`category_id`),
  KEY `fky_contact` (`contact_id`),
  KEY `fky_user` (`user_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_events` (
  `id`                        INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`                  INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`                     VARCHAR(200)              DEFAULT NULL,
  `alias`                     VARCHAR(100)              DEFAULT NULL,
  `description`               MEDIUMTEXT,
  `intro`                     MEDIUMTEXT,
  `public_id`                 INT(11) UNSIGNED          DEFAULT NULL,
  `activity_id`               INT(11) UNSIGNED          DEFAULT NULL,
  `date`                      DATETIME                  DEFAULT NULL,
  `enddate`                   DATETIME                  DEFAULT NULL,
  `vignette`                  VARCHAR(200)              DEFAULT NULL,
  `affiche`                   VARCHAR(200)              DEFAULT NULL,
  `published`                 TINYINT(1)       NOT NULL DEFAULT '1',
  `enrolment_enabled`         TINYINT(1)       NOT NULL DEFAULT '1',
  `enrolment_max_participant` INT(11) UNSIGNED          DEFAULT NULL,
  `contact_id`                INT(11) UNSIGNED          DEFAULT NULL,
  `proposal`                  INT(1)                    DEFAULT '0',
  `proposed_by`               INT(11) UNSIGNED          DEFAULT NULL,
  `agenda_id`                 INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`                   TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `access`                    INT(1)                    DEFAULT '0',
  `deleted`                   TINYINT(1)                DEFAULT '0',
  `hits`                      INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `intern_album_id`           INT(11) UNSIGNED          DEFAULT NULL,
  `extern_album_id`           INT(1)                    DEFAULT NULL,
  `lastmod_by`                INT(11) UNSIGNED          DEFAULT NULL,
  `created_date`              DATETIME                  DEFAULT NULL,
  `version`                   INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `section_id`                INT(11) UNSIGNED          DEFAULT NULL,
  `category_id`               INT(11) UNSIGNED          DEFAULT NULL,
  `ressource_id`              INT(11) UNSIGNED          DEFAULT NULL,
  `place_id`                  INT(11) UNSIGNED          DEFAULT NULL,
  `allow_overbooking`         INT(1) UNSIGNED           DEFAULT '0',
  `contact_person`            INT(11) UNSIGNED          DEFAULT NULL,
  `hot`                       TINYINT(1)       NOT NULL DEFAULT '0',
  `form_id`                   INT(11) UNSIGNED          DEFAULT '1',
  `contiguous_date`           TINYINT(1)                DEFAULT '0',
  `closingdate`               DATETIME                  DEFAULT NULL,
  `openingdate`               DATETIME                  DEFAULT NULL,
  `expirationdate`            DATETIME                  DEFAULT NULL,
  `showincalendar`            TINYINT(1)                DEFAULT '1',
  `adminLock`                 TINYINT(1)                DEFAULT '0',
  `ordering`                  INT(11)          NOT NULL DEFAULT '0',
  `additional_info`           MEDIUMTEXT,
  `enrolment_info`            MEDIUMTEXT,
  `metakey`                   MEDIUMTEXT,
  `metadesc`                  MEDIUMTEXT,
  `metarobots`                VARCHAR(200)              DEFAULT 'index, follow',
  `publishingdate`            DATETIME                  DEFAULT NULL,
  `showreadmore`              TINYINT(1)                DEFAULT '1',
  `cancelled`                 TINYINT(1)                DEFAULT '0',
  `checked_out`               INT(11)          NOT NULL,
  `checked_out_time`          DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`                INT(11)          NOT NULL,
  `contact_details_id`        INT UNSIGNED     NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_date` (`date`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_activiy` (`activity_id`),
  KEY `fky_public` (`public_id`),
  KEY `fky_section` (`section_id`),
  KEY `fky_category` (`category_id`),
  KEY `fky_places` (`place_id`),
  KEY `fky_agenda` (`agenda_id`),
  KEY `fky_albums` (`intern_album_id`),
  KEY `fky_contact` (`contact_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_forms` (
  `id`                  INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`            INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`               VARCHAR(100)              DEFAULT NULL,
  `alias`               VARCHAR(100)              DEFAULT NULL,
  `agenda_id`           INT(11) UNSIGNED          DEFAULT NULL,
  `description`         MEDIUMTEXT,
  `intro`               MEDIUMTEXT,
  `published`           TINYINT(1)       NOT NULL DEFAULT '1',
  `form_comp_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `form_comp_fields_id` VARCHAR(100)              DEFAULT NULL,
  `access`              TINYINT(1)                DEFAULT '0',
  `deleted`             TINYINT(1)                DEFAULT '0',
  `adminLock`           TINYINT(1)                DEFAULT '0',
  `version`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `ordering`            INT(11)          NOT NULL DEFAULT '0',
  `created_date`        DATETIME                  DEFAULT NULL,
  `proposed_by`         INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`             TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`          INT(11) UNSIGNED          DEFAULT NULL,
  `checked_out`         INT(11)          NOT NULL,
  `checked_out_time`    DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`          INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 3;

CREATE TABLE IF NOT EXISTS `#__allevents_formsfields` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(100)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `css_id`           VARCHAR(20)               DEFAULT NULL,
  `field_value`      VARCHAR(20)               DEFAULT NULL,
  `form_id`          INT(11) UNSIGNED          DEFAULT NULL,
  `type_id`          INT(11) UNSIGNED          DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `lenght`           INT(3)                    DEFAULT '40',
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `created_date`     DATETIME                  DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_form` (`form_id`),
  KEY `fky_type` (`type_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 4;

CREATE TABLE IF NOT EXISTS `#__allevents_formsfieldstype` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(100)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `defLenght`        INT(4)                    DEFAULT '0',
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `created_date`     DATETIME                  DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 3;

CREATE TABLE IF NOT EXISTS `#__allevents_groups` (
  `id`                            INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`                      INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`                         VARCHAR(100)              DEFAULT NULL,
  `alias`                         VARCHAR(100)              DEFAULT NULL,
  `description`                   MEDIUMTEXT,
  `intro`                         MEDIUMTEXT,
  `agenda_id`                     INT(11) UNSIGNED          DEFAULT NULL,
  `adminLock`                     TINYINT(1)       NOT NULL DEFAULT '0',
  `can_enrol`                     TINYINT(1)       NOT NULL DEFAULT '1',
  `enrol_auto`                    TINYINT(1)       NOT NULL DEFAULT '0',
  `can_accept_enrol_pending`      TINYINT(1)       NOT NULL DEFAULT '0',
  `can_accept_event_proposal`     TINYINT(1)       NOT NULL DEFAULT '0',
  `can_edit_published_events`     TINYINT(1)       NOT NULL DEFAULT '0',
  `can_post_html`                 TINYINT(1)       NOT NULL DEFAULT '0',
  `can_see_additionalinfo`        TINYINT(1)       NOT NULL DEFAULT '0',
  `can_see_albumphoto`            TINYINT(1)       NOT NULL DEFAULT '1',
  `can_see_comments`              TINYINT(1)       NOT NULL DEFAULT '1',
  `can_see_enrolmentinfo`         TINYINT(1)       NOT NULL DEFAULT '1',
  `can_see_enrolments`            TINYINT(1)       NOT NULL DEFAULT '1',
  `can_see_ressources`            TINYINT(1)       NOT NULL DEFAULT '1',
  `can_use_editor_buttons`        TINYINT(1)       NOT NULL DEFAULT '0',
  `can_publish_enrol`             TINYINT(1)       NOT NULL DEFAULT '0',
  `can_propose_event`             TINYINT(1)       NOT NULL DEFAULT '0',
  `can_publish_event`             TINYINT(1)       NOT NULL DEFAULT '0',
  `can_edit_own_event`            TINYINT(1)       NOT NULL DEFAULT '0',
  `can_edit_all_event`            TINYINT(1)       NOT NULL DEFAULT '0',
  `can_modify_settings`           TINYINT(1)       NOT NULL DEFAULT '0',
  `can_modify_mails`              TINYINT(1)       NOT NULL DEFAULT '0',
  `can_modify_css`                TINYINT(1)       NOT NULL DEFAULT '0',
  `can_change_text`               TINYINT(1)       NOT NULL DEFAULT '0',
  `can_delete`                    TINYINT(1)       NOT NULL DEFAULT '0',
  `allowUpload`                   TINYINT(1)       NOT NULL DEFAULT '0',
  `allowMakeFolder`               TINYINT(1)       NOT NULL DEFAULT '0',
  `allowKillUpload`               TINYINT(1)       NOT NULL DEFAULT '0',
  `allowChangeFolder`             TINYINT(1)       NOT NULL DEFAULT '0',
  `can_send_mails`                TINYINT(1)       NOT NULL DEFAULT '0',
  `showEnrolFormImmediatly`       TINYINT(1)       NOT NULL DEFAULT '0',
  `enrolWarning`                  MEDIUMTEXT,
  `published`                     TINYINT(1)       NOT NULL DEFAULT '1',
  `deleted`                       TINYINT(1)                DEFAULT '0',
  `ordering`                      INT(11)          NOT NULL DEFAULT '0',
  `version`                       INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `created_date`                  DATETIME                  DEFAULT NULL,
  `proposed_by`                   INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`                       TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`                    INT(11) UNSIGNED          DEFAULT NULL,
  `proposed_event_approved_auto`  TINYINT(1)       NOT NULL DEFAULT '0',
  `proposed_event_published_auto` TINYINT(1)       NOT NULL DEFAULT '0',
  `checked_out`                   INT(11)          NOT NULL,
  `checked_out_time`              DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`                    INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 9;

CREATE TABLE IF NOT EXISTS `#__allevents_links` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `ressource_id`     INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `titre`            VARCHAR(200)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `url`              VARCHAR(200)              DEFAULT NULL,
  `tooltip`          VARCHAR(200)              DEFAULT NULL,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `access`           TINYINT(1)       NOT NULL DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `created_date`     DATE             NOT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `ranking`          TINYINT(1)       NOT NULL DEFAULT '0',
  `link_type`        VARCHAR(255)              DEFAULT NULL,
  `article_id`       INT(11) UNSIGNED          DEFAULT NULL,
  `target`           TINYINT(1)                DEFAULT '0',
  `type`             TINYINT(1)                DEFAULT '0',
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_ressources` (`ressource_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_pictures` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(100)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `album_id`         INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `url`              VARCHAR(200)              DEFAULT NULL,
  `caption`          VARCHAR(400)              DEFAULT NULL,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `access`           TINYINT(1)       NOT NULL DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `created_date`     DATE             NOT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_album` (`album_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_places` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(200)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `map_id`           INT(11) UNSIGNED          DEFAULT NULL,
  `map_url`          VARCHAR(600)              DEFAULT NULL,
  `rue`              VARCHAR(80)               DEFAULT NULL,
  `numero`           VARCHAR(10)               DEFAULT NULL,
  `ville`            VARCHAR(40)               DEFAULT NULL,
  `codepostal`       VARCHAR(10)               DEFAULT NULL,
  `pays`             INT(11) UNSIGNED          DEFAULT NULL,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `default`          TINYINT(1)                DEFAULT '0',
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `vignette`         VARCHAR(100)              DEFAULT NULL,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `agenda_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `created_date`     DATE             NOT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `showmap`          TINYINT(1)                DEFAULT '1',
  `zoom`             INT(3)                    DEFAULT '14',
  `kmlfile`          VARCHAR(255)              DEFAULT NULL,
  `latitude`         VARCHAR(20)               DEFAULT NULL,
  `longitude`        VARCHAR(20)               DEFAULT NULL,
  `maptype`          TINYINT(1)                DEFAULT '0',
  `phone`            VARCHAR(30)               DEFAULT NULL,
  `fax`              VARCHAR(30)               DEFAULT NULL,
  `email`            VARCHAR(100)              DEFAULT NULL,
  `website`          VARCHAR(200)              DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  `country`          VARCHAR(100)              DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`),
  KEY `fky_country` (`pays`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_public` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(400)     NOT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `default`          INT(1)                    DEFAULT NULL,
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `agenda_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `vignette`         VARCHAR(100)              DEFAULT NULL,
  `created_date`     DATETIME                  DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_ressources` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(200)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `default`          TINYINT(1)       NOT NULL DEFAULT '0',
  `agenda_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `created_date`     DATE             NOT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_sections` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `asset_id`         INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `titre`            VARCHAR(100)              DEFAULT NULL,
  `alias`            VARCHAR(100)              DEFAULT NULL,
  `couleur`          CHAR(7)                   DEFAULT NULL,
  `couleur_texte`    CHAR(7)                   DEFAULT NULL,
  `access`           TINYINT(1)                DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `description`      MEDIUMTEXT,
  `intro`            MEDIUMTEXT,
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `created_date`     DATETIME                  DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `default`          TINYINT(1)       NOT NULL DEFAULT '0',
  `agenda_id`        INT(11) UNSIGNED          DEFAULT NULL,
  `vignette`         VARCHAR(100)              DEFAULT NULL,
  `image_bullet`     VARCHAR(100)              DEFAULT NULL,
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `version`          INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits`             INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `metakey`          MEDIUMTEXT,
  `metadesc`         MEDIUMTEXT,
  `metarobots`       VARCHAR(200)              DEFAULT 'index, follow',
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_access` (`access`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_agenda` (`agenda_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `#__allevents_settings` (
  `id`                                  INT(11)    NOT NULL AUTO_INCREMENT,
  `TitleStyle`                          VARCHAR(2)          DEFAULT 'h3',
  `ParticipantDefaultPhoto`             VARCHAR(250)        DEFAULT NULL,
  `ThumbnailSizeWidth`                  INT(4) UNSIGNED     DEFAULT '160',
  `ThumbnailSizeHeight`                 INT(4) UNSIGNED     DEFAULT '104',
  `PhotoParticipantSizeWidth`           INT(4) UNSIGNED     DEFAULT '50',
  `PhotoParticipantSizeHeight`          INT(4) UNSIGNED     DEFAULT '50',
  `PhotoAlbumFixedWidth`                INT(4) UNSIGNED     DEFAULT '640',
  `PhotoAlbumFixedHeight`               INT(4) UNSIGNED     DEFAULT '480',
  `AlbumPhoto`                          TINYINT(1)          DEFAULT '1',
  `ShowParticipantPhoto`                TINYINT(1)          DEFAULT '1',
  `JoomlaContact`                       TINYINT(1)          DEFAULT '1',
  `JoomlaContactCategory`               TINYINT(1)          DEFAULT '0',
  `JComments`                           TINYINT(1)          DEFAULT '1',
  `ShowRanking`                         TINYINT(1)          DEFAULT '0',
  `GPS`                                 TINYINT(1)          DEFAULT '1',
  `JComment_Connected`                  INT(1)              DEFAULT '0',
  `IntegrateGoogleMap`                  INT(1)              DEFAULT '1',
  `GoogleMapFixedWidth`                 INT(4) UNSIGNED     DEFAULT '0',
  `GoogleMapFixedHeight`                INT(4) UNSIGNED     DEFAULT '350',
  `FiltersOnTwoLines`                   INT(1)              DEFAULT '0',
  `FiltersShowAgenda`                   INT(1)              DEFAULT '1',
  `FiltersShowPublic`                   INT(1)              DEFAULT '1',
  `FiltersShowActivity`                 INT(1)              DEFAULT '1',
  `FiltersShowEventType`                INT(1)              DEFAULT '1',
  `FiltersShowYear`                     INT(1)              DEFAULT '1',
  `FiltersShowMonth`                    INT(1)              DEFAULT '1',
  `FiltersShowDay`                      INT(1)              DEFAULT '1',
  `FiltersShowProposition`              INT(1)              DEFAULT '1',
  `TranslateOnTheFly`                   INT(1)              DEFAULT '0',
  `CommunityBuilder`                    INT(1)              DEFAULT '1',
  `FiltersSearch`                       INT(1)              DEFAULT '1',
  `EventShowSummary`                    INT(1)              DEFAULT '1',
  `EventShowTitles`                     INT(1)              DEFAULT '1',
  `OpenMapsInANewWindow`                INT(1)              DEFAULT '0',
  `FiltersAreaCollapsed`                INT(1)              DEFAULT '1',
  `FiltersShowSection`                  INT(1)              DEFAULT '1',
  `FiltersShowCategory`                 INT(1)              DEFAULT '1',
  `FiltersShowPlaces`                   INT(1)              DEFAULT '1',
  `FiltersShowContacts`                 INT(1)              DEFAULT '1',
  `FiltersShowAccess`                   TINYINT(1)          DEFAULT '1',
  `FiltersShowRessources`               INT(1)              DEFAULT '1',
  `FiltersShowStates`                   INT(1)              DEFAULT '1',
  `ControlPanel_ShowSamples`            INT(1)              DEFAULT '1',
  `ControlPanel_ShowMigrate`            INT(1)              DEFAULT '1',
  `Allowemails`                         TINYINT(1)          DEFAULT '1',
  `ShowFilters`                         TINYINT(1)          DEFAULT '0',
  `ShowErrors`                          TINYINT(1)          DEFAULT '0',
  `ShowTextForm`                        TINYINT(1)          DEFAULT '0',
  `ShowTextCode`                        TINYINT(1)          DEFAULT '0',
  `FiltersShowSport`                    TINYINT(1)          DEFAULT '1',
  `FiltersNumberOfItems`                TINYINT(1)          DEFAULT '4',
  `ControlPanel_ShowHelp`               TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowForum`              TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowTutoriel`           TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowEnrolments`         TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowCountries`          TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowLoadImages`         TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowRessources`         TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowPlaces`             TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowActivity`           TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowPublic`             TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowSection`            TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowCategory`           TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowYourText`           TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowMails`              TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowCSS`                TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowAlbumPhoto`         TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowLinks`              TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowPhotos`             TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowRSSFeed`            TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowEventsToAccept`     TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowEnrolmentsToAccept` TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowWaitingList`        TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowStatistics`         TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowTop10`              TINYINT(1)          DEFAULT '1',
  `ControlPanel_ShowPermissions`        TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowUsers`              TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowForms`              TINYINT(1)          DEFAULT '0',
  `ControlPanel_ShowFormsFields`        TINYINT(1)          DEFAULT '0',
  `ShowParticipantName`                 TINYINT(1)          DEFAULT '1',
  `ShowParticipantAlias`                TINYINT(1)          DEFAULT '0',
  `ShowParticipantEnrolDate`            TINYINT(1)          DEFAULT '0',
  `ShowParticipantOrdering`             TINYINT(1)          DEFAULT '1',
  `ShowParticipantDossard`              TINYINT(1)          DEFAULT '1',
  `ShowParticipantTemps`                TINYINT(1)          DEFAULT '1',
  `ShowParticipantSection`              TINYINT(1)          DEFAULT '1',
  `ShowParticipantCategorie`            TINYINT(1)          DEFAULT '1',
  `ShowParticipantRang`                 TINYINT(1)          DEFAULT '1',
  `ShowParticipantRangCategorie`        TINYINT(1)          DEFAULT '1',
  `ShowParticipantCommentaire`          TINYINT(1)          DEFAULT '1',
  `ShowParticipantOrderField`           TINYINT(1)          DEFAULT '9',
  `FiltersShowProposedBy`               TINYINT(1)          DEFAULT '1',
  `FiltersShowHot`                      TINYINT(1)          DEFAULT '1',
  `TruncateTableWhenUninstall`          TINYINT(1)          DEFAULT '0',
  `DefaultBackgroundColor`              VARCHAR(7)          DEFAULT '#BEF781',
  `DefaultForegroundColor`              VARCHAR(7)          DEFAULT '#000000',
  `EventShowVignette`                   TINYINT(1)          DEFAULT '1',
  `EventShowPublic`                     TINYINT(1)          DEFAULT '1',
  `EventShowActivity`                   TINYINT(1)          DEFAULT '1',
  `EventShowEndDate`                    TINYINT(1)          DEFAULT '1',
  `EventShowAgenda`                     TINYINT(1)          DEFAULT '1',
  `EventShowSection`                    TINYINT(1)          DEFAULT '1',
  `EventShowCategory`                   TINYINT(1)          DEFAULT '1',
  `SourceParticipant`                   TINYINT(1)          DEFAULT '1',
  `ShowButtonPDF`                       TINYINT(1)          DEFAULT '0',
  `ShowButtonMail`                      TINYINT(1)          DEFAULT '1',
  `ShowButtonCSV`                       TINYINT(1)          DEFAULT '0',
  `ShowButtonPrint`                     TINYINT(1)          DEFAULT '1',
  `ShowButtonFB`                        TINYINT(1)          DEFAULT '1',
  `ShowButtonTwitter`                   TINYINT(1)          DEFAULT '1',
  `ShowButtonRSS`                       TINYINT(1)          DEFAULT '1',
  `OpenInNewWindow`                     TINYINT(1)          DEFAULT '0',
  `ShowHotEntry`                        TINYINT(1)          DEFAULT '0',
  `ShowAlbumPhotoEntry`                 TINYINT(1)          DEFAULT '0',
  `ShowRessourceEntry`                  TINYINT(1)          DEFAULT '0',
  `ShowLocalisationEntry`               TINYINT(1)          DEFAULT '0',
  `ShowSectionEntry`                    TINYINT(1)          DEFAULT '1',
  `ShowCategoryEntry`                   TINYINT(1)          DEFAULT '1',
  `ShowPublicEntry`                     TINYINT(1)          DEFAULT '0',
  `ShowActivityEntry`                   TINYINT(1)          DEFAULT '0',
  `ShowAgendaEntry`                     TINYINT(1)          DEFAULT '0',
  `ShowContactEntry`                    TINYINT(1)          DEFAULT '0',
  `ResetAlias`                          TINYINT(1)          DEFAULT '0',
  `Gravatar`                            TINYINT(1)          DEFAULT '1',
  `DefaultCountry`                      INT(11)    NOT NULL DEFAULT '1',
  `VignetteURL`                         VARCHAR(255)        DEFAULT 'thumbnails/default.png',
  `EnablePlugin`                        TINYINT(1)          DEFAULT '0',
  `ShowThumbnailTab`                    TINYINT(1)          DEFAULT '1',
  `ShowEnrolmentTab`                    TINYINT(1)          DEFAULT '1',
  `ShowParametersTab`                   TINYINT(1)          DEFAULT '1',
  `DefaultBullet`                       VARCHAR(255)        DEFAULT 'bullets/default.png',
  `ShowDescriptionEntry`                TINYINT(1)          DEFAULT '1',
  `ShowEndDateEntry`                    TINYINT(1)          DEFAULT '0',
  `ShowAliasEntry`                      TINYINT(1)          DEFAULT '0',
  `ShowPublishedEntry`                  TINYINT(1)          DEFAULT '0',
  `ShowContiguousDateEntry`             TINYINT(1)          DEFAULT '0',
  `ShowPropositionEntry`                TINYINT(1)          DEFAULT '0',
  `EmptyTables`                         TINYINT(1)          DEFAULT '0',
  `Zoom`                                INT(3)              DEFAULT '14',
  `MapType`                             TINYINT(1)          DEFAULT '0',
  `ShowTooltipsCaptions`                TINYINT(1)          DEFAULT '1',
  `ShowTooltipsTitle`                   TINYINT(1)          DEFAULT '1',
  `ShowTooltipsStartDate`               TINYINT(1)          DEFAULT '1',
  `ShowTooltipsEndDate`                 TINYINT(1)          DEFAULT '1',
  `ShowTooltipsVignette`                TINYINT(1)          DEFAULT '1',
  `ShowTooltipsAgenda`                  TINYINT(1)          DEFAULT '1',
  `ShowTooltipsActivity`                TINYINT(1)          DEFAULT '1',
  `ShowTooltipsPublic`                  TINYINT(1)          DEFAULT '1',
  `ToolTipVignetteWidth`                INT(3)              DEFAULT '94',
  `ToolTipVignetteHeight`               INT(3)              DEFAULT '92',
  `ToolTipWidth`                        INT(3)              DEFAULT '350',
  `ToolTipSticky`                       TINYINT(1)          DEFAULT '0',
  `PhotoAlbumMaxThumbnailHeight`        INT(4)              DEFAULT '52',
  `PhotoAlbumMaxThumbnailWidth`         INT(4)              DEFAULT '0',
  `PhotoAlbumMaxPhotoHeight`            INT(4)              DEFAULT '480',
  `PhotoAlbumMaxPhotoWidth`             INT(4)              DEFAULT '0',
  `ShowParticipantEnrolType`            TINYINT(1)          DEFAULT '1',
  `ShowParticipantEnrolTypeWhenPast`    TINYINT(1)          DEFAULT '0',
  `HideFrameDetail`                     TINYINT(1)          DEFAULT '0',
  `HideFrameDescription`                TINYINT(1)          DEFAULT '1',
  `HideFrameEnrolment`                  TINYINT(1)          DEFAULT '0',
  `HideFrameParameters`                 TINYINT(1)          DEFAULT '0',
  `HideFrameInformation`                TINYINT(1)          DEFAULT '0',
  `HideFrameThumbnail`                  TINYINT(1)          DEFAULT '1',
  `CanDeleteOverrideFiles`              TINYINT(1)          DEFAULT '1',
  `DatesUTC`                            TINYINT(1)          DEFAULT '1',
  `EnableSliding`                       TINYINT(1)          DEFAULT '1',
  `EventShowAuthor`                     TINYINT(1)          DEFAULT '1',
  `EventShowPlace`                      TINYINT(1)          DEFAULT '1',
  `Gradiant`                            TINYINT(1)          DEFAULT '1',
  `HideFrameSEO`                        TINYINT(1)          DEFAULT '1',
  `PhotoPosition`                       TINYINT(1)          DEFAULT '1',
  `ScrollWheel`                         TINYINT(1)          DEFAULT '0',
  `Shadow`                              TINYINT(1)          DEFAULT '1',
  `ShowButtonICS`                       TINYINT(1)          DEFAULT '0',
  `ShowButtonVCS`                       TINYINT(1)          DEFAULT '0',
  `ShowButtonGooglePlusOne`             TINYINT(1)          DEFAULT '1',
  `ShowButtonClipboard`                 TINYINT(1)          DEFAULT '0',
  `SlideAdditionalInfo`                 TINYINT(1) NOT NULL DEFAULT '0',
  `SlideAlbum`                          TINYINT(1) NOT NULL DEFAULT '1',
  `SlideComments`                       TINYINT(1) NOT NULL DEFAULT '1',
  `SlideContactPerson`                  TINYINT(1) NOT NULL DEFAULT '1',
  `SlideDescription`                    TINYINT(1) NOT NULL DEFAULT '0',
  `SlideEnrolForm`                      TINYINT(1) NOT NULL DEFAULT '0',
  `SlideEnrolmentInfo`                  TINYINT(1) NOT NULL DEFAULT '1',
  `SlideLinks`                          TINYINT(1) NOT NULL DEFAULT '0',
  `SlideParticipants`                   TINYINT(1) NOT NULL DEFAULT '1',
  `SlidePlace`                          TINYINT(1) NOT NULL DEFAULT '1',
  `ShowTooltipsCategory`                TINYINT(1)          DEFAULT '0',
  `ShowTooltipsSection`                 TINYINT(1)          DEFAULT '0',
  `ShowTooltipsPlace`                   TINYINT(1)          DEFAULT '0',
  `SummaryType`                         VARCHAR(50)         DEFAULT 'div',
  `NewEventEnrolmentEnabled`            TINYINT(1)          DEFAULT '1',
  `Key`                                 VARCHAR(50)         DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 2;

CREATE TABLE IF NOT EXISTS `#__allevents_users` (
  `id`               INT(11)          NOT NULL AUTO_INCREMENT,
  `group_id`         INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `user_id`          INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `published`        TINYINT(1)       NOT NULL DEFAULT '1',
  `ordering`         INT(11)          NOT NULL DEFAULT '0',
  `deleted`          TINYINT(1)                DEFAULT '0',
  `adminLock`        TINYINT(1)                DEFAULT '0',
  `created_date`     DATETIME                  DEFAULT NULL,
  `proposed_by`      INT(11) UNSIGNED          DEFAULT NULL,
  `lastmod`          TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastmod_by`       INT(11) UNSIGNED          DEFAULT NULL,
  `checked_out`      INT(11)          NOT NULL,
  `checked_out_time` DATETIME         NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by`       INT(11)          NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ndx_deleted` (`deleted`),
  KEY `ndx_published` (`published`),
  KEY `fky_group` (`group_id`),
  KEY `fky_users` (`user_id`)
)
  ENGINE = MyISAM
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

